import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Ticker from 'react-ticker';
import { useState } from 'react';

const Home: NextPage = () => {
  const [move, setMove] = useState(true);
  return (
    <div className={styles.container}>
      <Head>
        <title>Ticker App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Ticker speed={10} move={move}>
        {({ index }) => (
          <>
            <h1>This is the Headline of element #{index}!</h1>
          </>
        )}
      </Ticker>
      <main className={styles.main}>
        <button
          style={{
            width: 200,
            height: 100,
            backgroundColor: move ? 'red' : 'green',
            borderColor: move ? 'red' : 'green',
            borderRadius: 5,
          }}
          onClick={() => setMove((prev: boolean) => !prev)}
        >
          <p>{move ? 'Stop' : 'Start'}</p>
        </button>
        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Ticker</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by {'wawle'}
        </a>
      </footer>
    </div>
  );
};

export default Home;
