import type { NextPage } from 'next';
import Head from 'next/head';
import styles from '../styles/Home.module.css';
import Ticker from 'react-ticker';
import { useState } from 'react';

const Home: NextPage = () => {
  const [move, setMove] = useState(true);
  const [speed, setSpeed] = useState(10);
  return (
    <div className={styles.container}>
      <Head>
        <title>Ticker App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <Ticker speed={speed} move={move}>
        {({ index }) => (
          <>
            <h1>Berk gursoy finans</h1>
          </>
        )}
      </Ticker>
      <main className={styles.main}>
        <div>
          <div>
            <button
              style={{
                width: 200,
                height: 100,
                backgroundColor: move ? 'red' : 'green',
                borderColor: move ? 'red' : 'green',
                borderRadius: 5,
              }}
              onClick={() => setMove((prev: boolean) => !prev)}
            >
              <p>{move ? 'Stop' : 'Start'}</p>
            </button>
          </div>

          <div style={{ width: 100, marginTop: 10 }}>
            <div>
              <label htmlFor="Speed">Speed</label>
            </div>

            <input
              type="range"
              id="speed"
              name="speed"
              min="0"
              max="100"
              onChange={(event) => setSpeed(parseInt(event.target.value))}
              style={{ width: 198 }}
            />
          </div>
        </div>

        <h1 className={styles.title}>
          Welcome to <a href="https://nextjs.org">Ticker</a>
        </h1>
      </main>

      <footer className={styles.footer}>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by {'wawle'}
        </a>
      </footer>
    </div>
  );
};

export default Home;
